import express from "express";
const app = express();
import cors from "cors";
import dotenv from "dotenv";
import formidableExpress from "express-formidable";
import { connectDatabase } from "./config/MongoDb";
import importRoute from "./routers/importRoute";
import packageRoute from "./routers/packageRoute";
import orderRoute from "./routers/orderRoute";
import paymentRoute from "./routers/paymentRoute";
import brandRoute from "./routers/brandRoute";
import categoryRoute from "./routers/categoryRoute";
import additionalRoute from "./routers/additionalRoute";
import otherServiceRoute from "./routers/otherServiceRoute";
import orderStatusRoute from "./routers/orderStatusRoute";
import userAddressRoute from "./routers/userAddressRoute";
dotenv.config();
connectDatabase(); //connection db
app.use(cors());
app.use(formidableExpress());
app.use(express.static("uploads"));
app.use("/uploads", express.static("uploads"));
const PORT = process.env.APP_PORT || 3000;
app.get("/", async (req, res) => {
  res.send("katexoxo");
});
const defaultPath = "/kate-ckeck/api/katexoxo/";
app.use("/api/import/", importRoute);
app.use(defaultPath + "package", packageRoute);
app.use(defaultPath + "order", orderRoute);
app.use(defaultPath + "order-status", orderStatusRoute);
app.use(defaultPath + "payment", paymentRoute);
app.use(defaultPath + "brand", brandRoute);
app.use(defaultPath + "category", categoryRoute);
app.use(defaultPath + "additional", additionalRoute);
app.use(defaultPath + "other-service", otherServiceRoute);
app.use(defaultPath + "user-address", userAddressRoute);
app.listen(PORT, () => console.log(`Start ... http://localhost:${PORT}`));
